name: Swidux
options:
    bundleIdPrefix: io.clmntcrl
    deploymentTarget:
        iOS: 10.0
        macOS: '10.10'
        tvOS: 10.0
    indentWidth: 4
    tabWidth: 4
    usesTabs: false
targets:
    Swidux:
        platform: [macOS, iOS, tvOS]
        settings:
            FRAMEWORK_SEARCH_PATHS: $(inherited) $(PLATFORM_DIR)/Developer/Library/Frameworks
        scheme:
            testTargets: [SwiduxTests_$platform]
        sources: [Sources]
        type: framework
    SwiduxTests:
        dependencies: [{target: Swidux_$platform}]
        platform: [macOS, iOS, tvOS]
        sources:
            - path: Tests
              excludes:
                - LinuxMain.swift
        type: bundle.unit-test